### ISSUE TITLE
I think my giant scraper is breaking your site

### ISSUE THREAD

**Issue by nickjevershed** [openaustralia/morph#844] opened 2015-07-08 07:30 UTC
Page takes 29+ seconds to load, freezes when loaded. Are you loading in the entire console log? This is potentially very large! I'd provide more detail but can't see what's happening on the page.

[https://morph.io/nickjevershed/aec_party](https://morph.io/nickjevershed/aec_party)

**Comment by mlandauer** [comment] 2015-07-08 07:35
Yup that would be it. It loads the whole console log when it loads the page. As a workaround limit console output to something **not absolutely gigantic** and rerun the scraper. :-)

**Comment by henare** [comment] 2015-07-08 07:35
:) Duplicate of #612.

**Closed by henare** 2015-07-08 07:35 UTC

**Comment by nickjevershed** [comment] 2015-07-08 07:37
Haha, thanks. Will disable console ouput
