### ISSUE TITLE
Basic api request template

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#717] opened 2015-05-11 01:05 UTC
*As a user without experience using api's, when I want to use scraped data via the JSON API, give me an example of making a basic query in the language I write, to save me time and help me build what I want.*

This weekend I started on a small rails app that uses morph.io data via a json api. It took me a bit of research to find a clear answer on what the simplest way to make an API request and read the JSON data. I was excited to use the data, but this slowed me down and was frustrating. I think this is a roadblock that many users may face, that morph could help with.

Potential solution: On the api docs page provide examples of making simple api requests in a few key languages.

**Comment by mlandauer** [comment] 2015-05-11 01:06
Duplicate of #255

**Closed by mlandauer** 2015-05-11 01:06 UTC
Labels: UX
