### ISSUE TITLE
Scraper running too long

### ISSUE THREAD

**Issue by 43South** [openaustralia/morph#908] opened 2015-09-16 06:20 UTC
I've written a scraper that's dumping a large amount of data to the console (due to a bug). It's been running for several hours and I can't stop it from the webpage.
https://morph.io/43South/HuonValley

**Comment by 43South** [comment] 2015-09-16 23:35
To move things along I deleted the scraper completely. I hope this didn't create more problems with an orphan process or some such.

**Comment by henare** [comment] 2015-09-16 23:36
Thanks for reporting this, I guess it was a duplicate of #612.

**Closed by henare** 2015-09-16 23:36 UTC

**Comment by 43South** [comment] 2015-09-17 02:58
Yes, sorry, it's a duplicate.

**Comment by henare** [comment] 2015-09-17 03:09
@43South no sorry needed :smile:
