### ISSUE TITLE
Scrapers can appear to run for more than 24 hours

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#1050] opened 2016-08-03 02:55 UTC
There are currently 107 scrapers running according to this page: https://morph.io/scrapers/running

The first one in the list says it has been running for 3 months. Scrapers are supposed to be killed after 24 hours.

**Comment by mlandauer** [comment] 2016-08-07 20:26
Most of the ones on the list appear to be scrapers that have runs that haven't completed and don't have any jobs on the queue.

It's hard to guess what's happened to cause that situation. A couple I've looked at had huge number of log lines so I would guess that the problem was related to that.

I'm going to start by writing a little rake task to find running scrapers which don't have associated runs on the queue. Then, it will be easier to investigate each in turn and fix them up as I go.

**Comment by mlandauer** [comment] 2016-08-07 20:28
Completely forgot to mention one of the important bits - the reason we're seeing these long running scrapers (> 24 hours) is because they don't have associated docker containers. It's the docker containers that get stopped after 24 hours if they're running too long. If there isn't a container then nothing will get stopped.

**Comment by mlandauer** [comment] 2016-08-24 09:31
After fixing a number of things this is now fixed up. There were a few bugs that were contributing to jobs on the queue disappearing. There is now a rake task that can be used to double-check things and the main culprit I think (exploding memory usage of the background jobs) is fixed.

**Comment by henare** [comment] 2016-08-24 09:44
So. Awesome!

**Comment by equivalentideas** [comment] 2017-02-07 02:28
I'm seeing this again in production, reopening.

![screen shot 2017-02-07 at 1 25 57 pm](https://cloud.githubusercontent.com/assets/1239550/22675308/099b72e8-ed39-11e6-9e30-628c5a1f2881.png)

**Comment by equivalentideas** [comment] 2017-02-07 02:51
I've just run `bundle exec rake app:emergency:show_queue_run_inconsistencies RAILS_ENV=production` to show the list of "Unfinished runs attached to scrapers that do not have jobs on the queue"—this is [the task referred to above](https://github.com/openaustralia/morph/issues/1050#issuecomment-242007695).

I then took the array of runs and on the rails console, ran the following to show the names of scrapers in the stuck state:

```
unfinished_runs_fo_scrapers_without_jobs.each {|i| puts Run.find(i).scraper.full_name }
```

It appears that there's 116 scrapers in this state :( including lots of everypolitian and planningalerts scrapers:

- woodbine/sp_E5042_HLBC_gov
- eccoilmoro/Albo_pretorio_SantAgata_SS
- planningalerts-scrapers/salisbury
- lotsofdan/hide_my_ass_proxy_list_ip
- woodbine/sp_MOD017_MOD_gov
- mobeets/intriguing-things-scraper
- tmtmtmtm/scottish-parliament-wikidata
- tmtmtmtm/hungary-parliament
- woodbine/sp_NHTRX9NFT_EMASNT_gov
- tmtmtmtm/wallis-and-futuna-territorial-assembly-wikidata
- everypolitician-scrapers/ireland-positions
- woodbine/sp_E4201_BMBC_gov
- tmtmtmtm/liechtenstein-landtag-wikidata
- tmtmtmtm/denmark-folketing-wikidata
- everypolitician-scrapers/zambia-na-scraper
- woodbine/sp_E5048_SLBC_gov
- woodbine/sp_NFTRBK_WHNFT_gov
- DoomyTheFroomy/streets_by_immo_search_BB
- woodbine/sp_E0703_RACBC_gov
- woodbine/sp_E1421_ESCC_gov
- tmtmtmtm/montenegro-parldata
- woodbine/sp_NFTRKE_WHNFT_gov
- planningalerts-scrapers/development_assessment_panel_applications
- planningalerts-scrapers/kogarah
- carlplant/NHS_choices_GP_data
- woodbine/sp_DPM085_DFCALG_gov
- Abbie2020/sri_lanka_members_of_parliament
- LoveMyData/wingecarribee
- tmtmtmtm/guyana-parliament
- everypolitician-scrapers/dominican-republic-deputies-wikidata
- woodbine/sp_E0603_CEUA_gov
- planningalerts-scrapers/city_of_sydney
- tmtmtmtm/tanzania-parliament
- tmtmtmtm/moldova_parlament
- tmtmtmtm/sint-maarten-parliament
- tmtmtmtm/uganda-parliament-scraper
- everypolitician-scrapers/croatian-parliament-wikidata
- everypolitician-scrapers/nigeria-senate
- bcampbell/pcc-decisions-scraper
- kelpenhagen/Fire_Danger_Ratings_Tutorial
- tmtmtmtm/bahrain-council-of-representatives-wikipedia
- tmtmtmtm/nigeria-national-assembly
- ErinClark/td_EBRD
- LoveMyData/Bega_Valley_Applications_on_Exhibition
- woodbine/sp_FTRCDX_HDNHSFT_gov
- tmtmtmtm/suriname-nationale-assemblee
- everypolitician-scrapers/vanuatu-parliament
- woodbine/sp_NHTRXTFT_BASMHNFT_gov
- LoveMyData/South_Gippsland_Shire_DAs
- tmtmtmtm/pakistan-national-assembly-wikidata
- woodbine/sp_E5035_CLBC_gov
- ErinClark/td_ehub
- woodbine/sp_E1021_DCC_gov
- planningalerts-scrapers/nambucca
- woodbine/sp_DTI084_DFBIAS_gov
- planningalerts-scrapers/manly
- planningalerts-scrapers/maitland
- spendright/msd
- planningalerts-scrapers/albury
- woodbine/sp_E0104_NSC_gov
- richygit/fed_mp_data
- woodbine/sp_E4502_NUTCC_gov
- woodbine/sp_FTRA7X_UHBNHSFT_gov
- tmtmtmtm/us-congress-members-social-media
- everypolitician-scrapers/guam-legislature-members
- tmtmtmtm/belize-national-assembly-wikidata
- woodbine/sp_NFTRC1_BHNFT_gov
- tn2226/PPP_Scraper
- woodbine/sp_E5047_RUTBC_gov
- planningalerts-scrapers/ballarat
- pallih/fundargerdir_reykjavik
- tmtmtmtm/seychelles_national_assembly
- woodbine/sp_NHTRXGFT_SWYPNFT_gov
- everypolitician-scrapers/palau-delegates-wikidata
- robinmackenzie/Smartraveller_notices
- everypolitician-scrapers/dominican-republic-deputies
- woodbine/sp_E4703_KMC_gov
- woodbine/sp_FTRBBX_RNHRDNHSFT_gov
- tmtmtmtm/kiribati-parliament-wikidata
- woodbine/sp_E3720_WCC_gov
- tmtmtmtm/japan-house-of-representatives-wikidata
- LoveMyData/camden
- tupinek/gatema_news
- tmtmtmtm/jordan-house-of-representatives-wikidata
- woodbine/sp_E4606_WMBC_gov
- planningalerts-scrapers/uralla
- wilsonfreitas/MorthIO_TaxasVNATitulosPublicos_ANBIMA
- everypolitician-scrapers/samoa-parliament
- danishthanvi1/my-bd_cmp_list
- woodbine/sp_NFTR1H_BHNHST_gov
- Mortimerp9/flickr_camera_finder
- tmtmtmtm/ireland-kildarestreet
- woodbine/sp_NFTRHU_PHNFT_gov
- woodbine/sp_NHTRX5NFT_GWASNT_gov
- woodbine/sp_NFTR1F_IWNHST_gov
- woodbine/sp_E2401_LCC_gov
- tmtmtmtm/israel-knesset-members
- tmtmtmtm/romanian-parliament-wikidata
- tmtmtmtm/russian-duma-wikidata
- etraderz/me
- tmtmtmtm/algeria-national-assembly-wikidata
- pallih/fundargerdir_reykjanesbaer
- woodbine/sp_E4304_SMBC_gov
- woodbine/sp_E2721_NYCC_gov
- planningalerts-scrapers/goulburn
- ErinClark/td_proactis
- planningalerts-scrapers/edala
- vampireneo/farmy
- tmtmtmtm/niue-assembly
- tmtmtmtm/south-african-national-assembly-members-wikidata
- planningalerts-scrapers/moreland
- planningalerts-scrapers/ballina_shire
- woodbine/sp_NFTREF_RCHNFT_gov
- ebfhub/proxy_list
- woodbine/sp_DEC066_DOEACC_gov
- LoveMyData/bellingen-shire

**Comment by equivalentideas** [comment] 2017-02-07 03:13
Scrapers in this state are a bit invisible to us at the moment, unless we run this rake task. For example, they don't show up in the sidekiq queue, because there's no jobs, or the list of containers, because there's no containers. They don't show up on the [running scrapers page](https://morph.io/scrapers/running) because their `last_run.started_at` is `nil`. I'm going to try and track down why that is.

**Comment by equivalentideas** [comment] 2017-02-07 03:51
This is what I think is happening.

1. the scraper is [queued](https://github.com/openaustralia/morph/blob/master/app/models/scraper.rb#L249) and sent to the RunWorker which is managed by sidekiq.
2. before the scraper gets [to actually start running](https://github.com/openaustralia/morph/blob/master/lib/morph/runner.rb#L31), the job is lost. This means it never get's through to [`compile_and_start_run`](https://github.com/openaustralia/morph/blob/master/lib/morph/runner.rb#L86-L87) which is why there's no `started_at` set—and why it doesn't show up in list of running scrapers.

This is different from the [situation described earlier](https://github.com/openaustralia/morph/issues/1050#issuecomment-238106283) which was for scrapers that had started running but were [avoiding the 24 hour limit because their containers disappeared](https://github.com/openaustralia/morph/issues/1050#issuecomment-238106391). All the [116 scrapers currently in this state](https://github.com/openaustralia/morph/issues/1050#issuecomment-277885872) have no log lines, which suggests they haven't run.

So I think the immediate solution to get these running is to run `RunWorker.perform_async(run_id)` for [all those run listed above](https://github.com/openaustralia/morph/issues/1050#issuecomment-277885872). This will create new sidekiq jobs for them, which will either be activated or put into the retries queue.

I think the root cause is actually [Redis dropping the run's job when free memory dwindles](https://github.com/openaustralia/morph/issues/1056). All of the scrapers currently in this state where queued early last week when we were having bad disk space issues.

**Comment by equivalentideas** [comment] 2017-02-07 03:55
I've just run `[705431, 705435, 705448, 705449, 705457, 705460, 705472, 705475, 705477, 705478, 705482, 705485, 705487, 705495, 705499, 705519, 705534, 705537, 705539, 705546, 705547, 705552, 705557, 705566, 705569, 705571, 705577, 705588, 705591, 705594, 705609, 705612, 705619, 705630, 705633, 705643, 705645, 705646, 705647, 705649, 705652, 705653, 705655, 705656, 705664, 705666, 705670, 705672, 705673, 705678, 705681, 705682, 705683, 705684, 705687, 705691, 705694, 705702, 705708, 705709, 705710, 705712, 705718, 705722, 705724, 705725, 705728, 705729, 705733, 705737, 705744, 705746, 705747, 705748, 705749, 705754, 705758, 705761, 705765, 705791, 705805, 705809, 705813, 705865, 705879, 705884, 705891, 705896, 705897, 705898, 705899, 705923, 705935, 705938, 705939, 705940, 705941, 705942, 705943, 705944, 705945, 705946, 705947, 705948, 705949, 705950, 705951, 705952, 708505, 708506, 708507, 708508, 708509, 708510, 708511, 708512].each {|i| RunWorker.perform_async(i) }` on the Rails console, in production and now the inconsistencies rake task lists no Runs as expected.

**Comment by equivalentideas** [comment] 2017-02-07 03:58
I'll close this, since the actual cause here is https://github.com/openaustralia/morph/issues/1056 as far as we know.

**Closed by equivalentideas** 2017-02-07 03:58 UTC
Labels: bug
