### ISSUE TITLE
Scheduling a scraper for a certain time each day

### ISSUE THREAD

**Issue by jacksongs** [openaustralia/morph#871] opened 2015-07-16 00:26 UTC
Hey gang, great work on Morph.

I understand Morph runs scrapers in a queue making it difficult to schedule scrapers to run at specific times.

At the moment it's difficult to understand when or why the scraper automatically runs when it does. I suspect it may run approximately every 24 hours from when it was first set to automatically run.

But can you could include a setting that is something like "Run scraper every day at approximately XXam/pm"?

For example, I'm hoping to scrape some news headlines that are updated overnight. I want to run the scraper every day around 6am to get the morning's latest news. 

Thanks again.
J

**Comment by henare** [comment] 2015-07-16 06:44
Thanks @jacksongs!

Closing as this is a duplicate of #369.

**Closed by henare** 2015-07-16 06:44 UTC
