### ISSUE TITLE
Database Locked errors

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#749] opened 2015-05-20 10:04 UTC
Increasingly I'm getting "database locked" errors when running my scrapers — often on their first ever run.

e.g. I got this twice today on the https://morph.io/tmtmtmtm/rwanda-chamber-of-deputies scraper:

```
/app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/statement.rb:108:in `step': database is locked (SQLite3::BusyException)
	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/statement.rb:108:in `block in each'
	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/statement.rb:107:in `loop'
	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/statement.rb:107:in `each'
	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:158:in `to_a'
 	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:158:in `block in execute'
	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:95:in `prepare'
	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:134:in `execute'
	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite_magic-0.0.3/lib/sqlite_magic.rb:93:in `block in save_data'
	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite_magic-0.0.3/lib/sqlite_magic.rb:88:in `each'
	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite_magic-0.0.3/lib/sqlite_magic.rb:88:in `save_data'
	from /app/vendor/bundle/ruby/1.9.1/bundler/gems/scraperwiki-ruby-fc5017681250/lib/scraperwiki.rb:89:in `save_sqlite'
	from scraper.rb:45:in `block in <main>'
	from scraper.rb:31:in `each'
	from scraper.rb:31:in `<main>'
```

**Comment by mlandauer** [comment] 2015-05-20 10:12
I've seen that too. I've only seen it happening in the last 24 - 48 hours. I will investigate tomorrow morning. Cheers for the bug report!

**Comment by tmtmtmtm** [comment] 2015-05-20 10:21
Thanks. I've only really seen it in the last couple of day too. I rewrote this particular scraper to do the insert in one go at the end, rather than inside the loop, but it still errored even with a single write!

**Comment by mlandauer** [comment] 2015-05-21 01:36
This is what I know so far:

* the `SQLite3::BusyException` corresponds to the `SQLITE_BUSY` error from the underlying sqlite database (see https://github.com/sparklemotion/sqlite3-ruby/blob/b73fae5a4c515cbe2bbcf2bb01be4f8edd86d4b8/ext/sqlite3/exception.c#L23)
* This explains the `SQLITE_BUSY` error: https://www.sqlite.org/rescode.html#busy - this error normally indicates there is more than one process trying to write to the database at once.

There should only ever be one process writing to the database at once. This is the scraper process. There can be multiple processes reading from the database through the API but this shouldn't as far as I understand lock the database causing an `SQLITE_BUSY` error on the writer's side.

I had a look to double check that there weren't by some weird set of circumstances multiple scraper containers running (of the same scraper). There weren't while I could reproduce the error.

So, at the moment it's not clear why this is happening.

**Comment by mlandauer** [comment] 2015-05-21 01:37
One thing I failed to mention is that the api access is forced to be read-only so it should be impossible to do SQL queries through the API that write.

**Comment by tmtmtmtm** [comment] 2015-05-21 08:09
https://morph.io/tmtmtmtm/angola-national-assembly is giving the same problem now too. I haven't been able to complete a run of either scraper at all yet.

**Comment by tmtmtmtm** [comment] 2015-05-21 08:24
Ihttp://stackoverflow.com/a/5655874 suggests that it might be a result of un-`finalize`d queries. At a quick glance, I'm not so sure that this could be in play here as sqlite_magic doesn't seem to `prepare` the queries first anyway, but noting it here just in case it triggers any further thoughts.

**Comment by tmtmtmtm** [comment] 2015-05-22 14:41
Any suggestions even on a workaround for this? All three of my most recent scrapers are consistently failing every time, which is making Morph completely unusable for me now…

**Comment by tmtmtmtm** [comment] 2015-05-24 09:59
Putting an explicit `sleep 1` before each `ScraperWiki.save_sqlite` seemed to do the trick for https://morph.io/tmtmtmtm/rwanda-chamber-of-deputies

This obviously isn't ideal, but it's a usable workaround for now.

**Comment by mlandauer** [comment] 2015-05-25 09:03
Hi @tmtmtmtm - I've spent most of today trying to get to the bottom of this issue. Unfortunately not there yet but there are some sizeable clues.

Your workaround and scraper that reliably breaks is proving to be really helpful. Thanks for that.

It does appear to be some kind of interaction between the code that does the "realtime" update of the scraper page and the accessing of the database by the scraper itself.

For instance with your scraper https://morph.io/tmtmtmtm/rwanda-chamber-of-deputies you can also get rid of the locking issue by just removing the logging to standard out. I'm not for a minute suggesting that this is a solution, just another workaround.

It's the end of the day here now but I'll keep poking at this tomorrow and I'll let you know what happens!

**Comment by mlandauer** [comment] 2015-05-26 02:40
It's slightly troublesome that I can't reproduce this error either locally on my OS X box or when running locally as a full-blown VM of the whole working morph.io server.

So, I've resorted to doing some ugly hacks to test things out in production. The most recent change https://github.com/openaustralia/morph/commit/770cca229d77f2d44f117739d4ab3971ffb7feaa redirects sqlite database requests from the web-app [for a particular scraper](https://morph.io/mlandauer/rwanda-chamber-of-deputies) (which should all be read-only) to an entirely unrelated sqlite database.

This has the effect of ensuring that there is only the scraper process itself accessing the database.

Lo-and-behold even after running the scraper a dozen or more times I don't get the sqlite locking error. That's excellent news.

Now to the solution...

At the moment the sqlite database is shared between the docker container and the web app by mounting the filesystem inside the docker container. This has the advantage of being simple but obviously doesn't scale to the situation where we might want our docker containers to be running on a separate VM from our web app (see for example #647 which is a suggestion for a bit of rethink for the underlying architecture of the way docker containers are run as well as extracting a low-level scraper API out of morph.io).

One way we could ensure that there are never attempts to write to the sqlite database while reads are taking place is copy the sqlite database into the container before the scraper is run and copy it back out after it's finished. The copy of the database used by the web app is only ever read from and is only substituted for a new version after the end of every scraper run (whether successful or not).

This would also allow the docker server to potentially be running on a separate VM from the web app.

Since this fits nicely with the long term plan in #647 and would most likely resolve this issue I'm going to go ahead with implementing this. Wish me luck!

**Comment by tmtmtmtm** [comment] 2015-05-26 09:01
> One way we could ensure that there are never attempts to write to the sqlite database while reads are taking place is copy the sqlite database into the container before the scraper is run and copy it back out after it's finished. The copy of the database used by the web app is only ever read from and is only substituted for a new version after the end of every scraper run (whether successful or not).

That sounds like a good approach. Would it be possible to make the copying configurable based on the success? A way to say "don't replace the existing db if the scraper errors out" could be very handy.

**Comment by mlandauer** [comment] 2015-05-29 05:47
@tmtmtmtm this should all be fixed now as the sqlite database is now injected before the scraper run and extracted back at the end. I've split your suggestion above into a separate ticket #771.

I've rerun all the planningalerts scrapers that failed last night with sqlite locking errors and they've all run without any issues. So, looking good.

Please let me know if you come across any other issues.

**Closed by mlandauer** 2015-05-29 05:47 UTC
Labels: bug, in progress

**Comment by tmtmtmtm** [comment] 2015-05-30 15:32
Great, thanks!
