### ISSUE TITLE
Search for user doesn't work

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#614] opened 2015-04-20 05:04 UTC
I was looking for @equivalentideas and it doesn't find him: https://morph.io/search?utf8=%E2%9C%93&q=luke

**Comment by mlandauer** [comment] 2015-04-20 06:21
Because it's not implemented! :-)

Closing this as duplicate of #507

**Closed by mlandauer** 2015-04-20 06:21 UTC
Labels: bug, search

**Comment by henare** [comment] 2015-04-20 06:35
>Because it's not implemented! :-)

That'll do it! :)
