### ISSUE TITLE
scraper description doesn't update

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#708] opened 2015-05-06 08:03 UTC
I changed the description of my repo on github a few days ago, but the change hasn't been sync'd to morph yet.

I see the [morph page](https://morph.io/equivalentideas/nsw_police_media_releases) as:

> Scrape http://www.police.nsw.gov.au/news/media_release_archives to archive police media releases, which seem to be removed from their site after about a month.

[Github repo](https://github.com/equivalentideas/nsw_police_media_releases) as:

> NSW Police media releases (Australia).

**Comment by mlandauer** [comment] 2015-05-06 08:07
Duplicate of #207

**Closed by mlandauer** 2015-05-06 08:07 UTC
Labels: bug, Github (out of sync)
