### ISSUE TITLE
Logrotate /var/www/current/log/production.log

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#912] opened 2015-09-17 01:31 UTC
It's sitting at 3.4GB.

**Comment by henare** [comment] 2015-11-20 02:58
It was 6.7 GB. I just truncated it.

**Comment by mlandauer** [comment] 2016-07-04 23:27
This is a duplicate of #944

**Comment by mlandauer** [comment] 2016-07-04 23:28
What I didn't make clear is that #944 was fixed by adding log rotate to the rails log files. So, this is now fixed.

**Closed by mlandauer** 2016-07-04 23:27 UTC
Labels: devops, easy fix, enhancement, ready
