### ISSUE TITLE
can't delete scrapers

### ISSUE THREAD

**Issue by davidmarin** [openaustralia/morph#1085] opened 2016-09-08 17:26 UTC
I'm trying to delete my [msd](https://morph.io/spendright/msd) and [scrape-urls](https://morph.io/spendright/scrape-urls) scrapers, but when I try, I get a "We're sorry, but something went wrong" message.

**Comment by henare** [comment] 2016-09-09 01:17
@davidmarin thanks for reporting this. I'll close this as it's a duplicate of #1084.

**Closed by henare** 2016-09-09 01:17 UTC

**Comment by davidmarin** [comment] 2016-09-09 05:28
Thanks! Sorry to go, but an in-house strategy (using git-controlled YAML files) seems to be a better fit for what I'm doing.
