### ISSUE TITLE
Cannot view admin/runs page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#909] opened 2015-09-16 23:17 UTC
[Morph/production] Module::DelegationError: Run#cpu_time delegated to metric.cpu_time, but metric is nil: #<Run id: 164437, scraper_id: 3262, started_at: "2015-09-16 22:46:24", finished_at: nil, created_at: "2015-09-16 22:46:22", updated_at: "2015-09-16 23:00:53", status_code: nil, queued_at: "2015-09-16 22:46:22", auto: true, git_revision: "0dcc5fe6415019a68602d08a4cca8d48fe64becd", owner_id: 1177, wall_time: 0.0, tables_added: nil, tables_removed: nil, tables_changed: nil, tables_unchanged: nil, records_added: nil, records_removed: nil, records_changed: nil, records_unchanged: nil, ip_address: "172.17.5.113", connection_logs_count: 1045, docker_image: "9767ff7c8286">

## Backtrace

    line 15 of [PROJECT_ROOT]/app/models/run.rb: rescue in cpu_time
    line 15 of [PROJECT_ROOT]/app/models/run.rb: cpu_time
    line 17 of [PROJECT_ROOT]/app/admin/run.rb: block (3 levels) in <top (required)>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/35868/faults/15332947)

**Comment by henare** [comment] 2016-07-22 04:03
Duplicate of #879.

**Closed by henare** 2016-07-22 04:03 UTC
Labels: bug
