### ISSUE TITLE
Database file not writable?

### ISSUE THREAD

**Issue by wfdd** [openaustralia/morph#1064] opened 2016-08-11 12:23 UTC
My scrapers say 'nothing changed in the database' after each run and [this one](https://morph.io/wfdd/inatsisartut-scraper)'s database is empty after flushing it and re-running the scraper.  The scrapers themselves don't encounter any errors.  This started happening sometime in the last 24h.

**Comment by henare** [comment] 2016-08-13 06:32
Assigned @mlandauer since this has recently cropped up it may be because of recent changes.

**Comment by tmtmtmtm** [comment] 2016-08-13 07:19
We're seeing this a lot at the minute too — there have been two runs of https://morph.io/tmtmtmtm/singapore-parliament this morning, for example, after a database flush, neither of which have written any data.

**Comment by mlandauer** [comment] 2016-08-15 18:36
@wfdd by the looks of it your scrapers look okay now except for the specific one you mention that you flushed the database for. With that one sqlite database for some reason I don't understand had a very slightly different file permission than it should have. I don't know if this is the reason for the problem. But anyway I've deleted the sqlite file (of 0 length). Please try rerunning the scraper and see if that works now. Oh yes, and [I forked the scraper and ran it here](https://morph.io/morph-test-scrapers/inatsisartut-scraper) and it worked fine.

**Comment by mlandauer** [comment] 2016-08-15 18:37
@tmtmtmtm by the looks of it your scraper seems to have sorted itself out now. Whatever was causing this problem doesn't seem to be causing it now. Is that right?

**Comment by wfdd** [comment] 2016-08-15 19:42
All sorted I think.  Cheers.

**Comment by tmtmtmtm** [comment] 2016-08-16 09:03
@mlandauer yep. Would have liked to have been able to leave this one for you to investigate more fully, but we needed the data from it, so kicked it enough times until it ran successfully.

**Comment by achasik** [comment] 2016-08-21 06:10
Same problem here https://morph.io/achasik/torrents_ru

**Comment by achasik** [comment] 2016-08-21 06:23
Look at any new scraper - the same problem

**Comment by wfdd** [comment] 2016-08-22 22:34
It looks like the changes are lost in transit from the Docker container to wherever the database is subsequently stored, if that's any help.  Maybe something's up with the paths - DockerUtil discards FileNotFound errors, so you wouldn't really know it.

**Comment by achasik** [comment] 2016-08-24 10:48
OMG database not writeable again 
Just created new scraper in node.js from template and ran it
"Nothing changed in database"
https://morph.io/achasik/test

My old scraper affected too

**Comment by henare** [comment] 2016-09-04 22:15
[Reported by](https://help.morph.io/t/nothing-saving-to-database/251/17?u=henare) @achasik as happening again. I ran the [test scraper](https://morph.io/morph-test-scrapers/test-ruby) to confirm the issue (interestingly it had to reinstall it's dependencies) and it said:

>nothing changed in the database

So, as instructed by @mlandauer, that means the issue is happening and we need to restart the background queue processes:

`service morph restart`

And running the test scraper now works:

>1 record added, 1 record removed in the database

**Comment by henare** [comment] 2016-09-05 23:25
[Reported by](https://help.morph.io/t/nothing-saving-to-database/251/20?u=henare) @lowndsy as not working again. Confirmed on the test scraper. Restarted the background queue. Confirmed working again on the test scraper.

**Comment by henare** [comment] 2016-09-09 02:25
I just checked the test scraper again. It's not working again. Restarted and it's working again.

This is so weird - the morph server was restarted by Linode in emergency maintenance last night. Surely that counts as having restarted? That suggests this isn't like a memory leak where it starts happening after the queue's been running for a certain amount of time (which is the present theory).

**Comment by henare** [comment] 2016-09-14 04:35
@lovemydata just noticed that data wasn't been saved for his scraper so he pinged me in Slack. I confirmed the problem on the test scraper, restarted the queue, and confirmed it was resolved again.

**Comment by henare** [comment] 2016-09-15 05:25
[Reported by](https://help.morph.io/t/nothing-saving-to-database/251/22) @alisonkeen as not working again. Confirmed on the test scraper. Restarted the background queue. Confirmed working again on the test scraper.

**Comment by LoveMyData** [comment] 2016-09-16 10:43
Not working for this scraper. https://morph.io/LoveMyData/port_macquarie_hastings

**Comment by henare** [comment] 2016-09-18 23:46
@LoveMyData I just [tested the site](https://help.morph.io/t/nothing-saving-to-database/251/26?u=henare) and things seem to be working. Can you try again?

**Comment by equivalentideas** [comment] 2016-09-19 00:38
I'm getting this on https://morph.io/planningalerts-scrapers/ballina_shire.

**Comment by henare** [comment] 2016-09-19 00:49
Weird. The test scraper is still running fine: https://morph.io/morph-test-scrapers/test-ruby

I just restarted the queue and reran that scraper and it's working again:

>87 records added in the database

So this is a new discovery - this problem can show up on some scrapers but not others (maybe they ran on different background queue processes?).

**Comment by LoveMyData** [comment] 2016-09-19 02:10
@henare, Weird, just ran it again and it is working. Look at the history, there was few no records but all of the sudden, I am able to save to the DB.

But I am getting two console output
```
Getting data between 12/09/2016 and 19/09/2016, changable via MORPH_PERIOD environment
Getting data between 12/09/2016 and 19/09/2016, changable via MORPH_PERIOD environment
```
and there is only one 'print' command in php

**Comment by henare** [comment] 2016-09-30 00:25
Just [reported again](https://help.morph.io/t/nothing-saving-to-database/251/27?u=henare). This time I ran the test scraper twice and it ran OK. I've restarted the queue anyway as it may be the problem we were seeing above, where only one background process is affected.

**Comment by henare** [comment] 2016-10-04 23:38
At about 17:15 yesterday I noticed that the test scraper had failed. I restarted the queue but couldn't note it here because GitHub was down.

**Comment by wfdd** [comment] 2016-10-07 08:16
Was this closed accidentally?

**Comment by henare** [comment] 2016-10-10 02:44
@wfdd sure was, thanks for noticing this! Reopening.

**Comment by wfdd** [comment] 2016-10-10 20:37
Seeing at again [here](https://morph.io/wfdd/inatsisartut-scraper) and [here](https://morph.io/wfdd/cypriot-parliament-1r-scraper).

**Comment by henare** [comment] 2016-10-10 22:56
[Reporting again](https://help.morph.io/t/nothing-saving-to-database/251/30?u=henare). Queue restarted and verified working again.

**Comment by henare** [comment] 2016-10-12 23:45
[Reported again](https://help.morph.io/t/nothing-saving-to-database/251/32?u=henare). Didn't see the problem on the test scraper but restarted the queue anyway.

**Comment by wfdd** [comment] 2016-10-23 13:15
Seeing it again [here](https://morph.io/wfdd/cypriot-parliament-1r-scraper).

**Comment by henare** [comment] 2016-10-24 00:44
[Multiple reports](https://help.morph.io/t/nothing-saving-to-database/251/34?u=henare) of the problem again while I was away. I restarted the queue again at around 10:45.

I noticed that the queue had over 600 retries in it. I decided to restart the server to give us a fresh start. The shutdown got stuck on "asking all processes to terminate". I used the Linode console to issue a shutdown. It took 2.5 minutes and seemed to do a very hard shutdown (SysRq was mentioned). The boot seemed to happen quickly and without issue.

I then had to fix the no slots problem. I did this by copying the run ids of stopped containers and starting their runs again. That freed up 13 slots and things seem to be normal and we're starting to get through some of the backlog.

**Comment by henare** [comment] 2016-10-24 23:37
[Multiple](https://help.morph.io/t/nothing-saving-to-database/251/37) [reports](https://help.morph.io/t/my-scraper-stuck-what-to-do/156/38) of the problem again. 616 retries in the queue. Lots of stopped containers.

I restarted nginx and sidekiq because they both had a process at 15% memory. I noticed [a scraper](https://morph.io/dublicator/litres_scrapper) pegged at 100% CPU. Like last time, I copied all the stopped scraper run IDs into the console and started them. That freed up the queue. I checked again 10 minutes later and there were a bunch of stopped scrapers again. So I started jobs for them and they finished up and disappeared OK.

We've back to 540 jobs in the queue so I think it's getting better again. I'll make sure to ask @mlandauer to look at this as soon as he's in.

**Comment by mlandauer** [comment] 2016-10-25 03:23
Exploring a new hunch. I wonder whether we're hitting some kind of file descriptor limit. The odd thing is obviously that things are not working but there are no error messages. First just having a little bit of a poke around by running `lsof -p <pid>` on one of the sidekiq processes to see if anything looks suspicious. @henare does that raise any other thoughts from you?

**Comment by henare** [comment] 2016-10-25 03:37
@mlandauer hmm, not really. Wouldn't hitting that limit cause some kind of exception that we'd then see in Honeybadger?

**Comment by mlandauer** [comment] 2016-10-25 03:39
Yes, that's what I would expect normally. The only thing we really know at this stage is that restarting the queue fixes the problem. I'm struggling to even think of avenues to explore to fix this one... :-(

**Comment by henare** [comment] 2016-10-25 04:22
Another key bit of evidence from above. We've seen it happen on just one _process_ of Sidekiq before and not on the other. When I noticed that I also noticed that process was using a lot of memory, suggesting a scraper running under it was problematic.

**Comment by LoveMyData** [comment] 2016-11-25 00:42
Scraper failed to safe data... I did a 'Delete database', manually ran it, it ran ok but failed to show any data.

https://morph.io/LoveMyData/bankstown

**Comment by henare** [comment] 2016-11-25 01:00
Thanks @LoveMyData we haven't seen this for ages! I've confirmed it on the test scraper. It's worth noting that I restarted the server about an hour ago while working on the big queue backlog.

I've restarted Sidekiq and the test scraper is working again.

**Comment by tmtmtmtm** [comment] 2016-11-28 08:23
Happening again on https://morph.io/everypolitician-scrapers/bangladesh-parliament-wikidata — the last few runs didn't look like they were correct, so I deleted the database and re-ran. It said it completed fine, but didn't create a new DB. (NB we've been having a lot of issues over the last few days with scrapers seemingly stuck, queued for a long time. Triggering a manual run of a scraper seems to have had around a 25% chance of running instantly, 25% chance of being queued for a couple of hours, and 50% chance of being queued for ever.)

**Comment by wfdd** [comment] 2016-11-28 15:31
I'm also seeing this again with all of my scrapers.

**Comment by henare** [comment] 2016-12-03 06:59
@tmtmtmtm @wfdd ICYMI the queue is all [happy again for now](https://help.morph.io/t/morph-io-status-update-december-2016/297/2?u=henare).

**Comment by tmtmtmtm** [comment] 2017-01-14 16:24
This is happening again today — e.g. on https://morph.io/everypolitician-scrapers/netherlands-tweede-kamer-wikipedia

**Comment by equivalentideas** [comment] 2017-02-06 04:05
We're seeing this again https://help.morph.io/t/nothing-saving-to-database/251/44 and with the [test scraper](https://morph.io/morph-test-scrapers/test-ruby), I'll restart the morph service with `service morph restart`.

**Comment by equivalentideas** [comment] 2017-02-17 02:35
Saw this again today when a PlanningAlerts scraper was missing records https://morph.io/planningalerts-scrapers/marrickville .

A local person signed up to PlanningAlerts emailed to let us know we missed it ❤️

**Comment by tmtmtmtm** [comment] 2017-03-03 15:14
Looks like this has been happening for multiple days in a row with https://morph.io/everypolitician-scrapers/philippines-house-of-representatives — running locally picks up all 295 members just fine, but morph has been stuck with only 63 for a few days reporting 'nothing changed in the database' each time. 

We're also archiving the HTML of each page being visited into a `scraped_pages_archive` branch as we go, and can see from that that all of the pages are actually being successfully scraped on each run —  https://github.com/everypolitician-scrapers/philippines-house-of-representatives/commits/scraped-pages-archive

**Comment by tmtmtmtm** [comment] 2017-03-03 20:55
Looks like it's also happening with https://morph.io/wfdd/colombia-senado-wikidata-scraper, which is still getting data from Wikidata that was fixed on Feb 27, but has reported "nothing changed in the database" on the 4 runs since.

**Comment by henare** [comment] 2017-03-06 02:48
@tmtmtmtm I've restarted the morph service so hopefully it's fixed.

**Comment by wfdd** [comment] 2017-03-06 09:46
It isn't.

**Comment by wfdd** [comment] 2017-03-13 22:16
It's happening again: https://morph.io/wfdd/inatsisartut-scraper

**Comment by henare** [comment] 2017-03-14 00:21
I've restarted the service and it's working again on the test scraper.

In future can problem reports about this issue please be [made on the forum](https://help.morph.io/)? It doesn't feel like we're adding much to the knowledge about this issue by reporting recurrences here.

**Comment by chrismytton** [comment] 2017-04-13 17:00
I've just been investigating this and came across https://github.com/openaustralia/morph/commit/e281e1b669d93fdbbb7d186fdc7d411bda3df68d, which was committed two days before this issue was opened. The commit changes the behaviour of `Morph::DockerUtils.copy_files` to silently drop any [`Docker::Error::NotFoundError` exceptions](http://www.rubydoc.info/github/swipely/docker-api/Docker/Error/NotFoundError), which is "Raised when a request returns a 404".

My theory is that because those exceptions weren't being caught before that commit, Sidekiq was simply re-trying the job, but now they're being silently dropped the job is presumed successful, even though the file wasn't copied over.  I can't think of an easy way to test this theory though, suggestions welcome!

@mlandauer I don't suppose you remember any details about why https://github.com/openaustralia/morph/commit/e281e1b669d93fdbbb7d186fdc7d411bda3df68d was needed?

**Comment by LoveMyData** [comment] 2017-07-19 00:37
Happening again https://morph.io/LoveMyData/saplanningportal

**Comment by LoveMyData** [comment] 2017-10-03 02:41
nothing saved in the database.

eg. https://morph.io/LoveMyData/camden

**Comment by LoveMyData** [comment] 2017-10-13 04:30
nothing changed in the database

eg. https://morph.io/LoveMyData/city_of_adelaide_development_applications

**Comment by jnothman** [comment] 2017-11-15 23:42
I think given that this bug has been around for a while and no one yet understands how to solve it, it would be good to think about how to help users with it until it can be resolved, perhaps:
* a status page showing proportion of scrapers successfully changing database over time
* enhance the "completed successfully... nothing changed in the database" response with a link to a note about such issues or the status page
* automatically restart workers periodically

**Comment by LoveMyData** [comment] 2017-11-25 07:59
```nothing changed in the database``` strike again

https://morph.io/LoveMyData/north_sydney

**Comment by mlandauer** [comment] 2017-12-04 02:31
@chrismytton from memory (well actually mostly the commit message) that change was made because the new version of the docker api had changed behaviour. That method is supposed to return `nil` when no file is present. However, following the chain further through the code it does look like it will just get silently ignored if the `data.sqlite` file is not present which does seem extremely silly.

So, I think it would be good for a scraper to error if it doesn't generate an sqlite database. It might well be that the problem in this issue will then surface as an error on the scraper rather than the much harder to spot "nothing changed in the database" problem.

**Comment by mlandauer** [comment] 2017-12-04 06:04
Let's see if #1166 gets us any closer to fixing this problem!

**Comment by mlandauer** [comment] 2017-12-04 06:08
@chrismytton thanks so much for pointing out that bit of weird code. That was super helpful!

**Comment by mlandauer** [comment] 2017-12-05 02:09
About twenty minutes ago I pushed about 70 scraper runs on to the queue from the scheduled runs. I've noticed that this can cause the problem here.

I've confirmed that now scrapers will fail with the following message if this problem is occuring:
```
Scraper didn't create an SQLite database in your current working directory called
 data.sqlite. If you've just created your first scraper and not edited the code yet
 this is to be expected.
 
 To fix this make your scraper write to an SQLite database at data.sqlite.
 
 However, this could also be related to an intermittent problem which we're
 working hard to resolve: https://github.com/openaustralia/morph/issues/1064
```

I think this is a positive step in the right direction. At least it's now not a silent failure.

**Comment by mlandauer** [comment] 2017-12-05 03:51
The error above has a special status code "998" so we can now easily find runs where the problem has happened. Taking advantage of this to add something to the admin panel.

**Comment by vikash12345** [comment] 2018-01-30 12:14
I have 40+ scrapers in my account and the same issue here is the sample  URL
https://morph.io/vikash12345/Scraper1234
kindly check and let me know if anything wrong from my side.

Regards
Vikash Harjeewan

**Comment by vikash12345** [comment] 2018-02-01 05:56
https://morph.io/vikash12345/Caselaw_for_Sindh_High_Courts
Error of Database

**Comment by mlandauer** [comment] 2018-04-09 05:59
This has not happened in a long time now so closing. All the work on reducing memory spikes in the application have paid off.

**Closed by mlandauer** 2018-04-09 05:59 UTC

**Comment by codecakes** [comment] 2020-07-25 16:49
happening again: https://help.morph.io/t/nothing-saving-to-database/251/86?u=codecakes

**Comment by mlandauer** [comment] 2020-07-26 23:06
@codecakes I forked your repository to my own account and ran it on morph.io and got the same result: https://morph.io/mlandauer/beds. No records were written to the database.

Then, I cloned the repo and ran it locally and got exactly the same result. So whatever this problem is it's unlikely to have anything to do with morph.io specifically. I'd suggest you test the code locally on your own machine first, make sure it's doing what you expect and then run it on morph.io

**Comment by codecakes** [comment] 2020-07-27 10:08
> @codecakes I forked your repository to my own account and ran it on morph.io and got the same result: https://morph.io/mlandauer/beds. No records were written to the database.
> 
> Then, I cloned the repo and ran it locally and got exactly the same result. So whatever this problem is it's unlikely to have anything to do with morph.io specifically. I'd suggest you test the code locally on your own machine first, make sure it's doing what you expect and then run it on morph.io

im able to save data locally in data.sqlite; and its working when I m running it as server less function as well on one of the cloud services. Running with ScraperWiki locally saves data so not sure why it wouldn't work locally for you
