### ISSUE TITLE
As a developer, I'd like to be able to fork the data when I fork a code repository

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/morph#1217] opened 2019-05-15 06:24 UTC
https://morph.io/planningalerts-scrapers/tweed-shire is currently broken, but has existing data. I've forked https://github.com/planningalerts-scrapers/tweed-shire to https://github.com/jamezpolley/tweed-shire so I can make changes to the code, and I can run my fork on https://morph.io/jamezpolley/tweed-shire to test my changes.

But... I won't be testing against the existing data, so I won't notice if existing data gets changed by my new code.

**Comment by jamezpolley** [comment] 2019-05-15 06:25
It seems like we could potentially be more clever about this if we detected forks (#782 relates).

If my scraper does change data, I'd like to be able to reset it back to the state of the parent database.

**Comment by mlandauer** [comment] 2019-05-15 09:55
Duplicate of #17

**Closed by mlandauer** 2019-05-15 09:55 UTC
