### ISSUE TITLE
Excon::Errors::SocketError - invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#351] opened 2014-05-10 20:36 UTC
## Backtrace

    line 164 of [PROJECT_ROOT]/app/models/run.rb: log
    line 170 of [PROJECT_ROOT]/app/models/run.rb: block in go!
    line 127 of [PROJECT_ROOT]/app/models/run.rb: block (2 levels) in go_with_logging
    line 41 of [PROJECT_ROOT]/lib/morph/docker_runner.rb: block in run
    line 40 of [PROJECT_ROOT]/lib/morph/docker_runner.rb: run
    line 120 of [PROJECT_ROOT]/app/models/run.rb: go_with_logging
    line 169 of [PROJECT_ROOT]/app/models/run.rb: go!
    line 179 of [PROJECT_ROOT]/app/models/run.rb: synch_and_go!
    line 5 of [PROJECT_ROOT]/app/workers/run_worker.rb: perform

[View full backtrace and more info at honeybadger.io](https://www.honeybadger.io/inspector/p/35868/4795605)

**Comment by mlandauer** [comment] 2015-04-07 06:49
Duplicate of #529

**Closed** 2015-04-07 06:49 UTC
